
on: 
  push:
    branches:
      - main
name: ?? Deploy website on push

jobs:
  web-deploy:
    name: ?? Deploy website
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: ?? Get latest code
      uses: actions/checkout@v4
    # sync files via FTP
    - name: ?? Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}

    - name: Install NPM dependencies
      run: npm install

    - name: Build Vite assets
      run: npm run build

    - name: Upload to server
      run: rsync -avz --delete public/build user@host:/path/to/app/public/build
